### ISSUE TITLE
error authorizing context: authorization token required

### ISSUE THREAD

**Issue by ChrisB85** [zebox/registry-admin#20]
Hi,
I'm trying to run the app in localhost (for testing purposes for now) using files from _examples/token_auth. I am able to login, but when I hit "Sync" button i see some error in log:
`docker-registry-registry-1        | time="2023-08-09T18:24:10.564085228Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.19.9 http.request.host="registry:5000" http.request.id=10dd6015-f1da-4b4f-97af-62b008efad78 http.request.method=GET http.request.remoteaddr="172.19.0.2:38366" http.request.uri="/v2/_catalog?n=50&last=" http.request.useragent="Go-http-client/1.1"`

What can be the cause of this?

docker-compose file:
```
version: '2.1'
services:
  registry-admin:
    restart: unless-stopped
    image: zebox/registry-admin:master
    ports:
      - 80:80
    environment:
      - RA_CONFIG_FILE=/app/config/token-ra-config.yml
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./data:/app/data

  registry:
    restart: unless-stopped
    image: registry:2
    ports:
      - 50554:5000
    environment:
      - REGISTRY_AUTH_TOKEN_REALM=http://localhost/api/v1/registry/auth # <- !!! Change this for real hostname of RegistryAdmin and exposed port which accessible for docker clients
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./config/registry-config.yml:/etc/docker/registry/config.yml
    depends_on:
      - registry-admin
```

registry-config.yml:
```
version: 0.1

log:
  accesslog:
    disabled: false
  level: debug
  formatter: text
  fields:
    service: registry

storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true

http:
  addr: ":5000"
  net: tcp
  tls:
    certificate: /certs/cert.crt
    key: /certs/cert.key

auth:
  token:
    realm: http://localhost/api/v1/registry/auth  # <- external ip accessible for clients from outside of container
    service: container_registry
    issuer: registry_token_issuer
    rootcertbundle: /certs/cert.crt

notifications:
  events:
    includereferences: true
  endpoints:
    - name: ra-listener
      disabled: false
      url: http://registry-admin/api/v1/registry/events
      headers:
        Authorization: [Basic YWRtaW46c3VwZXItc2VjcmV0] # 'admin:super-secret' base64 encode string
      timeout: 1s
      threshold: 5
      backoff: 3s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
          - application/octet-stream
```

 token-ra-config.yml:
```
hostname: localhost

registry:
  host: https://registry
  port: 5000
  auth_type: token
  issuer: registry_token_issuer
  service: container_registry
  certs:
    path: /app/certs
    key: /app/certs/cert.key
    public_key: /app/certs/cert.pub
    ca_root: /app/certs/cert.crt
    ip: 127.0.0.1 # <- paste a real IP of docker host which publish the container
    fqdns: [registry, demo.host.local, localhost, registry.host.local]

store:
  type: embed
  admin_password: "super-secret"
  embed:
    path: /app/data/store.db
```

**Comment by zebox** [comment]
Hi @ChrisB85!

I suppose mistake in this
`realm: http://localhost/api/v1/registry/auth`

You should change `localhost` to hostname  which defined for the registry-admin container. In `docker-compose.yml` you can define `hostname` derective or use service name as hostname. 

In your case the registry-admin service has name `registry-admin` and this name available with mDNS inside containers stack network.

Target realm for token, in registry config file, should has hostname `registry-admin`:

`realm: http://registry-admin/api/v1/registry/auth`

**Comment by ChrisB85** [comment]
@zebox  Thak you for reply.

I made change you suggested, but unfortunately the `authorization token required` error still appears.

**Comment by zebox** [comment]
I will try reproduce this issue in my environment in nearest time. Until you can try use works step-by-step example from my [article](https://habr.com/ru/articles/709988), but it on russian language.

**Comment by zebox** [comment]
I checked config example and all work properly at me. 
But has some clarification:

1. Environment vars override config setting and you should change to `registry-admin` host name either in the env var `REGISTRY_AUTH_TOKEN_REALM` or comment out it (or remove) and define `realm` host name in registry config file only.
```yml
environment:
      - REGISTRY_AUTH_TOKEN_REALM=http://registry-admin/api/v1/registry/auth # <- !!! Change this for real host name of RegistryAdmin and exposed port which accessible for docker clients
```
2. For testing in local environment I recommend disable TLS for access to registry. It help you to avoid difficult with certificate authority trust issue. Otherwise you need configure self-signed certificate to trusted CA in registry container and insecure TLS  for a docker engine at client host. I will make step-by-step guide for this later.

This works example for your testing:

docker-compose.yml 
```yml
version: '2.1'
services:
  registry-admin:
    hostname: registry-admin
    restart: unless-stopped
    image: zebox/registry-admin:master
    ports:
      - 8080:80
    environment:
      - RA_CONFIG_FILE=/app/config/token-ra-config.yml
    volumes:
      - ./certs:/app/certs
      - ./config:/app/config
      - ./data:/app/data

  registry:
    restart: unless-stopped
    image: registry:2
    ports:
      - 50554:5000
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./config/registry-config.yml:/etc/docker/registry/config.yml
    depends_on:
      - registry-admin
```
registry-config.yml

```yml
version: 0.1

log:
  accesslog:
    disabled: false
  level: debug
  formatter: text
  fields:
    service: registry

storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true

http:
  addr: ":5000"
  net: tcp
  # disable TLS access for testing in local env
  #tls:
    #certificate: /certs/cert.crt
    #key: /certs/cert.key

auth:
  token:
    realm: http://registry-admin/api/v1/registry/auth  # <- external ip accessible for clients from outside of container
    service: container_registry
    issuer: registry_token_issuer
    rootcertbundle: /certs/cert.crt

notifications:
  events:
    includereferences: true
  endpoints:
    - name: ra-listener
      disabled: false
      url: http://registry-admin/api/v1/registry/events
      headers:
        Authorization: [Basic YWRtaW46c3VwZXItc2VjcmV0] # 'admin:super-secret' base64 encode string
      timeout: 1s
      threshold: 5
      backoff: 3s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
          - application/octet-stream
```
token-ra-config.yml:
```yml
hostname: 127.0.0.1

registry:
  host: http://registry
  port: 5000
  auth_type: token
  issuer: registry_token_issuer
  service: container_registry
  certs:
    path: /app/certs
    key: /app/certs/cert.key
    public_key: /app/certs/cert.pub
    ca_root: /app/certs/cert.crt
    ip: {YOUR-OUTSIDE-CONTAINER-IP} # <- paste a real IP of docker host which publish the container
    fqdns: [demo.host.local, localhost, registry.host.local]  # <- paste your fqdns

store:
  type: embed
  admin_password: "super-secret" # you should delete this string after database created
  embed:
    path: /app/data/store.db
```
